# Site settings
title: Jac Prada
email: jacopo.prada@gmail.com
url: https://jacprada.github.io
description: "Jac Prada - Web Developer | Digital Strategist | Growth Hacker"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#e5a54b'

# Footer settings
footer: Jac Prada

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: linkedin
    url: https://linkedin.com/in/jacprada
  - title: github
    url: https://github.com/jacprada

# Build settings
markdown: kramdown
permalink: pretty
